Module4 task1
leann-fraoigh/six-cities-react-project pull request #1
Opened 2022-10-05 11:44 UTC by leann-fraoigh

Задание 4.13. Обратная сторона реальности

2022-10-09 17:52 UTC, rewoop requested changes

2022-10-09 17:52 UTC, rewoop commented on project/src/components/app/app.tsx
> +type AddProps = {
Почему не просто пропс или AppProps?

2022-10-09 17:52 UTC, rewoop commented on project/src/components/app/app.tsx
> +  offers: Offer[]
Эту штуку можно вынести в '../../types/offer' и сделать такой тип `export type Offers = Offer[];`

2022-10-09 17:52 UTC, rewoop commented on project/src/mocks/offers.tsx
> +export const offers: Offer[] = [
Это не реактовский файл, поэтому разрешение должно быть .ts , а не .tsx

2022-10-09 17:52 UTC, rewoop commented on project/src/mocks/offers.tsx
> +export const offers: Offer[] = [
И здесь тоже можно использовать тип Offers, про что я в App написал

2022-10-09 17:52 UTC, rewoop commented on project/src/components/offer-card/offer-card.tsx
> +function OfferCard(props: OfferCardProps): JSX.Element {
А почему все функции приложения написаны через function, а не стрелками?

2022-10-09 17:52 UTC, rewoop commented on project/src/components/offers-cards-list/offers-cards-list.tsx
> +  offers: Offer[],
С типом тоже самое, что и в App я написал

2022-10-09 17:52 UTC, rewoop commented on project/src/components/offers-cards-list/offers-cards-list.tsx
> +  const setActiveCard = useState<string | undefined>(undefined)[1];
А расскажи, что ты здесь делаешь? 
useState используется же таким образом - `const [activeCard, setActiveCard] = useState<string | undefined>(undefined);` после чего используется activeCard после её установки, а сейчас получается, что ты её только устанавливаешь и никак не используешь

2023-02-26 19:24 UTC, leann-fraoigh commented on project/src/components/offers-cards-list/offers-cards-list.tsx
> +  const setActiveCard = useState<string | undefined>(undefined)[1];
Тут по ТЗ пока нужно только сохранять состояние, использоваться оно будет для чего-то в будущем. Так что пока написано как написано, чтобы избежать ругани на неиспользуемую переменную.

2023-02-26 19:24 UTC, leann-fraoigh commented on project/src/components/app/app.tsx
> +type AddProps = {
Очепяточка.

2023-03-03 16:23 UTC, rewoop approved these changes

2023-03-03 16:30 UTC, merged